### ISSUE TITLE
can it sticky footer?

### ISSUE THREAD

**Issue by xrmeng** [yahoo/react-stickynode#110]
can it sticky footer?

**Comment by rikkit** [comment]
```css
.sticky-inner-wrap {
  top: calc(100% - <height of your footer>);
}
```
