### ISSUE TITLE
z-index should not be applied when element isn't sticky

### ISSUE THREAD

**Issue by JohannesHansen** [yahoo/react-stickynode#93]
`.sticky-inner-wrapper` always seem to have `z-index` set. Expected behaviour would be for `z-index` to only be applied when the element actually is sticky.

This currently causes issues with z-index on child elements.

**Comment by rikkit** [comment]
Dunno about whether this should change, but you can override this behaviour with CSS

```css
.sticky-outer-wrapper:not(.active) {
  .sticky-inner-wrapper {
    z-index: unset !important;
  }
}
```
